using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using WebAPIDevOps.ORM;
using WebAPIDevOps.ORM.SubSonic.SQLGeneration.Schema;

namespace WebAPIDevOps.Server.Databases.Users
{
    public class UserRecordRelator
    {
        public const string FetchQueries = "SELECT * FROM users";
    }
    [TableName("users")]
    public class UserRecord : IAutoGeneratedRecord
    {
        
        [PrimaryKey("Id")]
        public int Id
        {
            get;
            set;
        }
        public string Name
        {
            get;
            set;
        }
        public string Email
        {
            get;
            set;
        }
        public string PasswordHash
        {
            get;
            set;
        }
        public byte Lang
        {
            get;
            set;
        }
        public string Sid
        {
            get;
            set;
        }
        public DateTime CreationDate
        {
            get;
            set;
        }
        public DateTime? LastConnection
        {
            get;
            set;
        }
    }
}